### Investigating the files and preparing a sample submissin file detailing what should be mentioned and how to prepare such a file 


As with prior years, each game has a unique ID created by concatenating the season in which the game was played and the two team's respective TeamIds. For example, "2026_1101_1102" indicates a hypothetical matchup between team 1101 and 1102 in the year 2026. You must predict the probability that the team with the lower TeamId beats the team with the higher TeamId. Note that the men's teams and women's TeamIds do not overlap.

The resulting submission format looks like the following, where Pred represents the predicted probability that the first team will win:

ID,Pred
2026_1101_1102,0.5
2026_1101_1103,0.5
2026_1101_1104,0.5
...

In [2]:


import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns


from src.data_loader import (
    load_teams, load_seasons, load_regular_season_results,
    load_tourney_results, load_seeds, validate_data_coverage
)
from src.utils import check_data_quality, get_season_summary

# Plotting settings
plt.style.use('seaborn-v0_8-darkgrid')
sns.set_palette('husl')
%matplotlib inline

pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 100)

## Regular season processing

In [ ]:
men_regular = load_regular_season_results('M','compacted')
men_regular.head(10)

   Season  DayNum  WTeamID  WScore  LTeamID  LScore WLoc  NumOT
0    1985      20     1228      81     1328      64    N      0
1    1985      25     1106      77     1354      70    H      0
2    1985      25     1112      63     1223      56    H      0
3    1985      25     1165      70     1432      54    H      0
4    1985      25     1192      86     1447      74    H      0
5    1985      25     1218      79     1337      78    H      0
6    1985      25     1228      64     1226      44    N      0
7    1985      25     1242      58     1268      56    N      0
8    1985      25     1260      98     1133      80    H      0
9    1985      25     1305      97     1424      89    H      0

In [ ]:
men_regular = load_regular_season_results('M','detailed')

men_regular.head(10)

In [4]:
women_regular = load_regular_season_results('W')
women_regular.head(10)

   Season  DayNum  WTeamID  WScore  LTeamID  LScore WLoc  NumOT
0    1998      18     3104      91     3202      41    H      0
1    1998      18     3163      87     3221      76    H      0
2    1998      18     3222      66     3261      59    H      0
3    1998      18     3307      69     3365      62    H      0
4    1998      18     3349     115     3411      35    H      0
5    1998      18     3435      65     3172      63    H      0
6    1998      18     3443      89     3257      73    H      0
7    1998      19     3119      75     3217      47    H      0
8    1998      19     3139      74     3103      58    H      0
9    1998      19     3141      73     3387      55    H      0